.TH BITCREDIT-CLI "1" "February 2016" "bitcredit-cli 0.12"
.SH NAME
bitcredit-cli \- a remote procedure call client for Bitcredit Core. 
.SH SYNOPSIS
bitcredit-cli [options] <command> [params] \- Send command to Bitcredit Core. 
.TP
bitcredit-cli [options] help \- Asks Bitcredit Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the bitcredit-cli program. bitcredit-cli is an RPC client used to send commands to Bitcredit Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBbitcreditd\fP, \fBbitcredit.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
